version: "3.8"

services:
  postgresdb:
    build: db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  pgadmin:
    image: dpage/pgadmin4:9.11.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    ports:
      - $PGADMIN_LOCAL_PORT:$PGADMIN_DOCKER_PORT
    depends_on:
      - postgresdb
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  app:
    depends_on:
      - postgresdb
    build: batwatch-app
#    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_LOCAL_PORT:$DEBUG_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:$POSTGRESDB_DOCKER_PORT/$POSTGRESDB_DATABASE",
        "spring.datasource.username" : "$POSTGRESDB_USER",
        "spring.datasource.password" : "$POSTGRESDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "app.bootstrap.admin.username" : "$APP_BOOTSTRAP_ADMIN_USERNAME",
        "app.bootstrap.admin.password" : "$APP_BOOTSTRAP_ADMIN_PASSWORD"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  pgadmin-data: